# ------------------------------------------------------------------------------
#
# Copyright 2011, 2012, 2013 Brent L. Brock and the Craighead Institute
#
# This file is part of Wild Planner.
#
# Wild Planner is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Wild Planner is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Wild Planner in the file named LICENSE.TXT.  If not, see <http://www.gnu.org/licenses/>.
#
# ------------------------------------------------------------------------------
# connected_export.py
# Created on: 2012-11-07 15:52:12.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy


# Local variables:
Bobcat_Hab_merge = "Bobcat_Hab_merge"
bobcat_scen1_lnk_100_img = "bobcat_scen1_lnk_100.img"
RasterT_badg_li1_shp = "C:\\WORKSPACE\\RasterT_bobcat_2.shp"
Output_Feature_Class = "C:\\WORKSPACE\\RasterT_bobcat_2_Erase.shp"
Output_Feature_Class__3_ = "C:\\WORKSPACE\\RasterT_bobcat_2_Erase_Multi.shp"
Output_Layer = "RasterT_bobcat_2_Erase_Multi"
Output_Layer__2_ = "Bobcat_Hab_merge_Layer"
Bobcat_Hab_merge__2_ = "Bobcat_Hab_merge_Layer"
RasterT_badg_li1_Erase_Layer = "RasterT_bobcat_2_Erase_Multi"
Bobcat_Hab_merge__3_ = "Bobcat_Hab_merge_Layer"
RasterT_badg_li1_Erase_Layer__2_ = "RasterT_bobcat_2_Erase_Multi"
RasterT_bobcat_2_Erase_Multi = "RasterT_bobcat_2_Erase_Multi"
Output_Feature_Class__2_ = "C:\\WORKSPACE\\RasterT_bobcat_2_Erase_Multi1.shp"

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(bobcat_scen1_lnk_100_img, RasterT_badg_li1_shp, "NO_SIMPLIFY", "VALUE")

# Process: Erase
arcpy.Erase_analysis(RasterT_badg_li1_shp, Bobcat_Hab_merge, Output_Feature_Class, "")

# Process: Multipart To Singlepart
arcpy.MultipartToSinglepart_management(Output_Feature_Class, Output_Feature_Class__3_)

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(Output_Feature_Class__3_, Output_Layer, "", "", "Shape Shape VISIBLE NONE;FID FID VISIBLE NONE;ID ID VISIBLE NONE;GRIDCODE GRIDCODE VISIBLE NONE;ORIG_FID ORIG_FID VISIBLE NONE")

# Process: Make Feature Layer (2)
arcpy.MakeFeatureLayer_management(Bobcat_Hab_merge, Output_Layer__2_, "", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;ID ID VISIBLE NONE;GRIDCODE GRIDCODE VISIBLE NONE;area area VISIBLE NONE;sizeclass sizeclass VISIBLE NONE;sqkm sqkm VISIBLE NONE")

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(Output_Layer__2_, "NEW_SELECTION", "\"GRIDCODE\" = 1")

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(Output_Layer, "BOUNDARY_TOUCHES", Bobcat_Hab_merge__2_, "", "NEW_SELECTION")

# Process: Select Layer By Attribute (2)
arcpy.SelectLayerByAttribute_management(Output_Layer__2_, "NEW_SELECTION", "\"GRIDCODE\" = 2")

# Process: Select Layer By Location (2)
arcpy.SelectLayerByLocation_management(RasterT_badg_li1_Erase_Layer, "BOUNDARY_TOUCHES", Bobcat_Hab_merge__3_, "", "SUBSET_SELECTION")

# Process: Select Layer By Attribute (3)
arcpy.SelectLayerByAttribute_management(RasterT_badg_li1_Erase_Layer__2_, "SUBSET_SELECTION", "GRIDCODE = 1")

# Process: Copy Features
arcpy.CopyFeatures_management(RasterT_bobcat_2_Erase_Multi, Output_Feature_Class__2_, "", "0", "0", "0")

